image: registry.gitlab.com/canya-com/node-build-container:1.2

variables:
  APP_PATH: /builds/$CI_PROJECT_PATH

before_script:
  - cd $APP_PATH

stages:
  - build
  - deploy_hosting
  - deploy_functions

build:dist:staging:
  stage: build
  environment: staging
  artifacts:
    name: "canwork-webui dist"
    paths:
      - $APP_PATH/dist
  script:
    - yarn
    - echo -n "+ current working path:" && pwd
    - echo $ENVIRONMENT_STAGING >> $APP_PATH/src/environments/environment.staging.ts
    - yarn run build:staging

build:dist:production:
  stage: build
  environment: production
  artifacts:
    name: "canwork-webui dist"
    paths:
      - $APP_PATH/dist
  script:
    - yarn
    - echo -n "+ current working path:" && pwd
    - echo $ENVIRONMENT_PROD >> $APP_PATH/src/environments/environment.prod.ts
    - yarn run build:prod

deploy:hosting:staging:
  stage: deploy_hosting
  environment: staging
  dependencies:
    - build:dist:staging
  script:
    - firebase deploy --only hosting --token "$FIREBASE_CI_AUTH_TOKEN" -P staging-can-work
    - firebase deploy --only firestore:rules --token "$FIREBASE_CI_AUTH_TOKEN" -P staging-can-work
    - firebase deploy --only firestore:indexes --token "$FIREBASE_CI_AUTH_TOKEN" -P staging-can-work

deploy:hosting:production:
  stage: deploy_hosting
  environment: production
  when: manual
  dependencies:
    - build:dist:production
  script:
    - firebase deploy --only hosting --token "$FIREBASE_CI_AUTH_TOKEN" -P canwork-io
    - firebase deploy --only firestore:rules --token "$FIREBASE_CI_AUTH_TOKEN" -P canwork-io
    - firebase deploy --only firestore:indexes --token "$FIREBASE_CI_AUTH_TOKEN" -P canwork-io

deploy:functions:staging:
  stage: deploy_functions
  environment: staging
  when: manual
  script:
    - cd $APP_PATH/functions
    - yarn
    - yarn -g firebase-tools@latest
    - cd ..
    - firebase use staging --token "$FIREBASE_CI_AUTH_TOKEN"
    - firebase functions:config:set algolia.appid="$FIREBASE_ALGOLIA_APPID" --token "$FIREBASE_CI_AUTH_TOKEN"
    - firebase functions:config:set algolia.apikey="$FIREBASE_ALGOLIA_APIKEY" --token "$FIREBASE_CI_AUTH_TOKEN"
    - firebase functions:config:set algolia.providerindex="$FIREBASE_ALGOLIA_STAGINGINDEX" --token "$FIREBASE_CI_AUTH_TOKEN"
    - firebase functions:config:set sendgrid.apikey="$FIREBASE_SENDGRID_APIKEY" --token "$FIREBASE_CI_AUTH_TOKEN"
    - firebase functions:config:set fbadmin.project_id="$FIREBASE_PROJECT_ID_STAGING" --token "$FIREBASE_CI_AUTH_TOKEN"
    - firebase functions:config:set fbadmin.client_email="$FIREBASE_CLIENT_EMAIL_STAGING" --token "$FIREBASE_CI_AUTH_TOKEN"
    - firebase functions:config:set fbadmin.private_key="$FIREBASE_PRIVATE_KEY_STAGING" --token "$FIREBASE_CI_AUTH_TOKEN"
    - firebase functions:config:set fbadmin.database_url="$FIREBASE_DATABASE_URL_STAGING" --token "$FIREBASE_CI_AUTH_TOKEN"
    - firebase functions:config:set dev.authkey="$FIREBASE_DEV_AUTHKEY" --token "$FIREBASE_CI_AUTH_TOKEN"
    - firebase deploy --only functions --token "$FIREBASE_CI_AUTH_TOKEN" -P staging-can-work

deploy:functions:production:
  stage: deploy_functions
  environment: production
  when: manual
  script:
    - cd $APP_PATH/functions
    - yarn
    - yarn -g firebase-tools@latest
    - cd ..
    - echo $ENVIRONMENT_PROD >> $APP_PATH/src/environments/environment.prod.ts
    - firebase use staging --token "$FIREBASE_CI_AUTH_TOKEN"
    - firebase functions:config:set algolia.appid="$FIREBASE_ALGOLIA_APPID" --token "$FIREBASE_CI_AUTH_TOKEN"
    - firebase functions:config:set algolia.apikey="$FIREBASE_ALGOLIA_APIKEY" --token "$FIREBASE_CI_AUTH_TOKEN"
    - firebase functions:config:set algolia.providerindex="$FIREBASE_ALGOLIA_PROVIDERINDEX" --token "$FIREBASE_CI_AUTH_TOKEN"
    - firebase functions:config:set sendgrid.apikey="$FIREBASE_SENDGRID_APIKEY" --token "$FIREBASE_CI_AUTH_TOKEN"
    - firebase functions:config:set fbadmin.project_id="$FIREBASE_PROJECT_ID" --token "$FIREBASE_CI_AUTH_TOKEN"
    - firebase functions:config:set fbadmin.client_email="$FIREBASE_CLIENT_EMAIL" --token "$FIREBASE_CI_AUTH_TOKEN"
    - firebase functions:config:set fbadmin.private_key="$FIREBASE_PRIVATE_KEY" --token "$FIREBASE_CI_AUTH_TOKEN"
    - firebase functions:config:set fbadmin.database_url="$FIREBASE_DATABASE_URL" --token "$FIREBASE_CI_AUTH_TOKEN"
    - firebase functions:config:set dev.authkey="$FIREBASE_DEV_AUTHKEY" --token "$FIREBASE_CI_AUTH_TOKEN"
    - firebase deploy --only functions --token "$FIREBASE_CI_AUTH_TOKEN" -P canwork-io
