language: node_js
node_js:
  - 9.1.0
script:
  - npm install -g npm@6.1.0
  - npm install -g tslint typescript
  - npm install
  - cd functions/ && npm install; cd ../
install:
  - npm install -g firebase-tools
after_success:
  - firebase use staging
  - firebase functions:config:set algolia.appid=$ALGOLIA_APPID
  - firebase functions:config:set algolia.apikey=$ALGOLIA_APIKEY
  - firebase functions:config:set algolia.providerindex=$ALGOLIA_PROVIDERINDEX
  - firebase functions:config:set sendgrid.apikey=$SENDGRID_APIKEY
  - firebase functions:config:set dev.authkey=$DEV_API_KEY
  - firebase functions:config:set fbadmin.project_id=$FBADMIN_PROJECT_ID
  - firebase functions:config:set fbadmin.client_email=$FBADMIN_CLIENT_EMAIL
  - firebase functions:config:set fbadmin.private_key="$FBADMIN_PRIVATE_KEY"
  - firebase functions:config:set fbadmin.client_email=$FBADMIN_CLIENT_EMAIL
  - firebase functions:config:set fbadmin.database_url=$FBADMIN_DATABASE_URL
  - ng build --environment=staging --aot --build-optimizer
  - firebase deploy --token $FIREBASE_TOKEN
